# The Bear Cub mix release. Build knowledge lives with the code it builds
# (design §7); the homeassistant repo pins a rev of this repo and imports
# nix/module.nix, which callPackages this file.
#
# Dependencies are one Nix derivation each (nix/deps.nix, generated by
# deps_nix and kept in sync by the deps.get/deps.update aliases), so a code
# change rebuilds only the app; deps rebuild only when mix.lock or config/
# changes.
{ lib
, beamPackages
, callPackages
, fetchFromGitHub
, sqlite
, tailwindcss_4
, esbuild
}:

let
  mixNixDeps = callPackages ./deps.nix {
    inherit beamPackages;
    overrides = final: prev: {
      # Link the NIF against nixpkgs' sqlite instead of compiling the
      # bundled amalgamation. EXQLITE_USE_SYSTEM also makes exqlite's
      # mix.exs drop its precompiler, so no precompiled-NIF download is
      # attempted (unreachable in the sandbox anyway).
      exqlite = prev.exqlite.override {
        buildInputs = [ sqlite ];
        env.EXQLITE_USE_SYSTEM = "1";
      };
    };
  };

  # Asset-only git dep (app: false, compile: false): deps_nix omits it from
  # deps.nix (it special-cases only heroicons), so it is pinned by hand.
  # Bump rev + hash together with mix.exs / mix.lock.
  daisyui = fetchFromGitHub {
    owner = "saadeghi";
    repo = "daisyui";
    rev = "22ecff57f2c391b80a75617325748cf4d13fdf47"; # v5.5.20
    hash = "sha256-I2LI9VYVxQcvoMDgDWmvNyQToS1rFm12V167YxqDs24=";
  };
in
beamPackages.mixRelease {
  pname = "bear-cub";
  version = "0.1.0";

  src = lib.cleanSourceWith {
    src = ../.;
    filter = path: type:
      let name = baseNameOf path; in
      !(builtins.elem name [ ".git" "_build" "deps" "node_modules" ".dexter" "_work" "docs" "nix" ])
      && !(lib.hasSuffix ".db" name)
      && !(lib.hasSuffix ".db-shm" name)
      && !(lib.hasSuffix ".db-wal" name);
  };

  inherit mixNixDeps;

  # Some build steps (elixir_make's cache, tailwind) expect a writable
  # $HOME; the sandbox default is the nonexistent /homeless-shelter.
  preConfigure = ''
    export HOME="$TEMPDIR"
  '';

  # mixRelease only links deps/<name> for store paths with a src/ subdir
  # (buildMix outputs). These two are raw sources that assets.deploy reads:
  # app.css @plugins daisyui, and assets/vendor/heroicons.js resolves
  # ../../deps/heroicons/optimized. Full-repo fetches keep the same
  # subpaths the sparse checkouts expose in dev.
  postConfigure = ''
    ln -sfn ${mixNixDeps.heroicons} deps/heroicons
    ln -sfn ${daisyui} deps/daisyui
  '';

  # Build digested assets inside the sandbox with nixpkgs-provided
  # binaries (design §7); config.exs picks the paths up from these
  # env vars. deps.loadpaths first: external tasks need the no-deps-
  # check workaround (phoenixframework/phoenix#2690).
  #
  # Runs in postBuild, not preBuild: mixRelease's default buildPhase is
  # `preBuild; mix compile; postBuild`, and assets.deploy needs the app
  # already compiled (Phoenix.LiveView.ColocatedCSS only writes
  # phoenix-colocated/bear_cub/colocated.css during that compile — running
  # this earlier makes tailwind fail to resolve that import).
  postBuild = ''
    export MIX_TAILWIND_PATH="${lib.getExe tailwindcss_4}"
    export MIX_ESBUILD_PATH="${lib.getExe esbuild}"
    mix do deps.loadpaths --no-deps-check, assets.deploy
  '';

  # Single-node app: no distribution, no cookie management needed.
  removeCookie = false;
}
