import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :bear_cub, BearCubWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# No force_ssl: Bear Cub is deliberately HTTP-only on LAN + tailnet — the
# network is the trust boundary (design D5/§7), and the kiosk tablet hits
# the raw LAN IP, which an HTTPS redirect would break.

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
